name: CI

on:
  push:
    tags:
      - '**'
    branches:
      - '**'

env:
  NAME: iptsd
  SCRIPTS: ./.github/scripts
  BRANCH_STAGING: u/staging

jobs:
  checkout:
    name: Prepare workspace
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Archive workspace
      uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: .

  build-arch:
    name: Build Arch Linux Package
    container: archlinux/archlinux
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - name: Restore workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace

    - name: Install dependencies
      run: bash $SCRIPTS/pkg-arch.sh install

    - name: Build package
      run: bash $SCRIPTS/pkg-arch.sh build

    - name: Sign package
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: bash $SCRIPTS/pkg-arch.sh sign

    - name: Prepare release
      run: bash $SCRIPTS/pkg-arch.sh release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: arch-latest
        path: release

  build-deb:
    name: Build Debian Package
    container: debian:bullseye
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - name: Restore workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace

    - name: Install dependencies
      run: bash $SCRIPTS/pkg-debian.sh install

    - name: Build package
      run: bash $SCRIPTS/pkg-debian.sh build

    - name: Sign package
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: bash $SCRIPTS/pkg-debian.sh sign

    - name: Prepare release
      run: bash $SCRIPTS/pkg-debian.sh release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debian-latest
        path: release

  build-f37:
    name: Build Fedora 37 package
    container: fedora:37
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - name: Restore workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace

    - name: Install build dependencies
      run: bash $SCRIPTS/pkg-fedora.sh install

    - name: Build package
      run: bash $SCRIPTS/pkg-fedora.sh build

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: bash $SCRIPTS/pkg-fedora.sh sign

    - name: Prepare release
      run: bash $SCRIPTS/pkg-fedora.sh release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fedora-37-latest
        path: release

  build-f36:
    name: Build Fedora 36 package
    container: fedora:36
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - name: Restore workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace

    - name: Install build dependencies
      run: bash $SCRIPTS/pkg-fedora.sh install

    - name: Build package
      run: bash $SCRIPTS/pkg-fedora.sh build

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: bash $SCRIPTS/pkg-fedora.sh sign

    - name: Prepare release
      run: bash $SCRIPTS/pkg-fedora.sh release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fedora-36-latest
        path: release

  release:
    name: Publish release
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    needs: [build-deb, build-arch, build-f37, build-f36]
    runs-on: ubuntu-latest
    steps:
    - name: Download Debian artifacts
      uses: actions/download-artifact@v3
      with:
        name: debian-latest
        path: debian-latest

    - name: Download Arch Linux artifacts
      uses: actions/download-artifact@v3
      with:
        name: arch-latest
        path: arch-latest

    - name: Download Fedora 37 artifacts
      uses: actions/download-artifact@v3
      with:
        name: fedora-37-latest
        path: fedora-37-latest

    - name: Download Fedora 36 artifacts
      uses: actions/download-artifact@v3
      with:
        name: fedora-36-latest
        path: fedora-36-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*-latest/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  repo-arch:
    name: Update Arch Linux package repository
    container: archlinux/archlinux
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - name: Restore workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: arch-latest
        path: arch-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.SURFACE_BOT_TOKEN }}
        GIT_REF: ${{ github.ref }}
      run: bash $SCRIPTS/repo-arch.sh $NAME

  repo-deb:
    name: Update Debian package repository
    container: debian:bullseye
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - name: Restore workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: debian-latest
        path: debian-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.SURFACE_BOT_TOKEN }}
        GIT_REF: ${{ github.ref }}
      run: bash $SCRIPTS/repo-debian.sh $NAME

  repo-f37:
    name: Update Fedora 37 package repository
    container: fedora:37
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - name: Restore workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: fedora-37-latest
        path: fedora-37-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.SURFACE_BOT_TOKEN }}
        GIT_REF: ${{ github.ref }}
      run: bash $SCRIPTS/repo-fedora.sh $NAME 37

  repo-f36:
    name: Update Fedora 36 package repository
    container: fedora:36
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - name: Restore workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: fedora-36-latest
        path: fedora-36-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.SURFACE_BOT_TOKEN }}
        GIT_REF: ${{ github.ref }}
      run: bash $SCRIPTS/repo-fedora.sh $NAME 36
